### PR TITLE
feat(download): Show download progress

### PR DESCRIPTION
**Pull request by zachmullen**
This adds a progress bar that tracks download progress when `openRemoteDataset` is called. One issue -- I have no idea where in the GUI it should go, any thoughts?

### CODE REVIEW

**Comment by jourdain** [comment]
I was thinking on the top right since there are some room there.

**Comment by jourdain** [comment]
Should we merge?

**Comment by zachmullen** [comment]
It's good to go in from my perspective; as long as you are happy with it we can merge it.

**Comment by jourdain** [comment]
I'll merge it along with my other branch (once vtk.js has a new version with my fix. ;-)

Thanks for your contribution.

**Pull request merged**
