### PR TITLE
fix(glanceProxyConfig): dynamically register linked properties

### PR DESCRIPTION
**Pull request by agirault**
- Possible thanks to: https://github.com/Kitware/vtk-js/commit/28f40b2
- Define previous links from: https://github.com/Kitware/vtk-js/pull/587

### CODE REVIEW

**Comment by agirault** [comment]
WIP: need Kitware/vtk-js#587 merged (and package-lock.json updated after npm install)

**Comment by agirault** [comment]
@thewtex you will probably want to do the same thing for [itk-vtk-viewer](https://github.com/Kitware/itk-vtk-image-viewer/) if you update to [vtk.js ^6.2.8](https://github.com/Kitware/vtk-js/pull/587)

**Comment by agirault** [comment]
package-lock.json updated

**Comment by agirault** [comment]
should be good @jourdain ?

**Comment by jourdain** [comment]
yes should be

**Pull request merged**
