### PR TITLE
Cornerstone integration

### PR DESCRIPTION
**Pull request by floryst**
Adds cornerstone viewers to medical mode.

Currently supported tools: window/level, zoom (right mouse button), pan (middle mouse button press), length, angle, and pixel probe.

Reference issue: #18

Still to add:

- [x] stack scrolling with wheel
- [x] other tools (angle, length, pixel probe, elliptical roi)
- [x] listing of tools in the view similar to VolView's widget list

Issues:

- synchronized window/level is a bit laggy.
- Scrolling through slices when the active view is a 3D view is slow

NOTE: this is quite a big PR, and some things still need to be moved out to vtkjs, e.g. the ImageSlice filter, or some things need to use existing vtk.js classes, e.g. ImageDataToCornerstoneImage. Some clean-up will be necessary. Also, further testing will be needed to catch corner cases.

cornerstone2

Not displayed in the above preview: window/level synchronization between views, zoom, pan.

### CODE REVIEW

**Comment by floryst** [comment]
Updated video and notes; see first post above. Updates: tool measurement listing and stack scrolling with mouse wheel. Another performance-related minor issue has been noted.

**Comment by jourdain** [comment]
Should this be merged at some point?

**Comment by floryst** [comment]
Yep, going to do that today after I fix merge conflicts.

**Pull request merged**
