### PR TITLE
New progress bar and about page

### LINKED ISSUE #22: Kitware Logo and link to a Kitware page
One panel or popup should be an "About" panel that talks about Kitware, gives a link to Kitware.com, gives a link to paraview.org, and mentions that we provide consulting support.   This popup/panel could also link to a "Help" page (or be the help page).

### PR DESCRIPTION
**Pull request by floryst**
WIP Adds a status bar with a progress bar, and an about page button. Reference: #22.

Todo:
- [x] fill out help/info page
- [x] show custom progress text

Design and UI critique would be appreciated, @aylward @jourdain 

progress_and_about

### CODE REVIEW

**Comment by jourdain** [comment]
Can you shrink the top bar too? I feel it is too big.

**Comment by jourdain** [comment]
Right now, the status bar looks like a 1990 app... I'm wondering if we can provide similar features with a more modern look&feel. Unless we try to reproduce that feel on purpose?

**Comment by floryst** [comment]
Yeah I'll shrink the top bar. Icons feel too big up there.

Yeah, status bars are outdated when esp it comes to webapps. I'm not sure where else I can put the loading bar. Maybe a notification/toast message off in a corner that can't be dismissed until loading is done? If we later decide to use the progress bar for other things (filters, etc.), then we need to also make sure it's not intrusive to the user.

**Comment by jourdain** [comment]
I was thinking a 2 pixel progress bar at the bottom with the text showing as overlay either on the left/right like chrome does to show link path when overlaying a link.

**Comment by floryst** [comment]
Or maybe at have the progress bar at the top with a "halo", similar to how youtube does it. The overlay idea is good, maybe put it at the right so it's not covered by chrome and firefox on page load.

**Comment by jourdain** [comment]
The top is good. Also I don't think you would like to click on the `About page` or `change layout` when something is loading. So you could use that top bar for printing some text which the progress update...

**Comment by floryst** [comment]
Here is the current WIP gif. I don't think it matters if the user changes layout or views the about page while loading, e.g. loading a network dataset. I do like the idea of repurposing the top bar for progress text. Maybe some overlay notification/toast, or maybe just replacing the toolbar contents with loading info?

glance1

**Comment by jourdain** [comment]
yes for => ` just replacing the toolbar contents with loading info`

**Comment by floryst** [comment]
I've updated the top-most comment with a new video of the progress bar, progress text, and about box. At this point it's pretty much ready to go after any comments.

**Pull request merged**
